In [56]:
import numpy as np

ls = [1,2,3,4,5]
a = np.array(ls)

print(a)
print(a.data)
print(a.size)
print(a.shape)
print(a.dtype)
print(a.strides)


[1 2 3 4 5]
5
(5,)
int32
(4,)


In [57]:
a = [[1,2,3],[2,3,4],[3,4,5]]
b = np.array(a)
print(b)
print(b.data)
print(b.size)
print(b.shape)
print(b.dtype)
print(b.strides)

[[1 2 3]
 [2 3 4]
 [3 4 5]]
9
(3, 3)
int32
(12, 4)


first things are pretty self explanatory ,lets talk about the last.
- Strides -> it has 2 things is 2d array and 1 thing is 1D array.
- first thing says, for reaching next element in that COLOUMN, means 0,0 to 1,0 we need to cross 12 bites (consider pointer is at entry of first element, so 3 jump 4*3)
- second thing shows jumping to the next element in that row, we need to cross 4 bytes.

NOTE- this 4 bytes can be 8 bytes in other system depending upon system configuration.

### SLICING

1D array

In [58]:
ls = [1,2,3,4,5]
a = np.array(ls)

print(ls[0:])
print(a[1:4])

[1, 2, 3, 4, 5]
[2 3 4]


Same way as normal list

2D array

In [59]:
a = [[1,2,3],[2,3,4],[3,4,5]]
b = np.array(a)
print(b)
print(a[1][2])
print(b[1][2])
print(b[1,2])   #new way
#print(a[1,2])  # not possible with list

[[1 2 3]
 [2 3 4]
 [3 4 5]]
4
4
4


In [60]:
print(a[2][0:2]) # with list
print(b[2][0:2]) #with numpy array

[3, 4]
[3 4]


In [61]:
print(a[2][1:])  #with list
print(b[2][1:])  #with numpy array

[4, 5]
[4 5]


In [62]:
a = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
b = np.array(a)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [63]:
b[2][1:]

array([10, 11, 12])

In [55]:
b[2,1:]  #can be written like this

array([10, 11, 12])

question is, i want 8,12,16 from this now

In [41]:
b[1:][3]

IndexError: index 3 is out of bounds for axis 0 with size 3

- so it is throwing error,
- lets break it down. 

In [65]:
print(a[1:])
print()
print(b[1:])

[[5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]

[[ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


now we are accessing 3rd index from here, which is not present ie it has 2 elements.

In [66]:
print(a[1:][2])
print()
print(b[1:][2])

[13, 14, 15, 16]

[13 14 15 16]


see the second index

In [69]:
b[1:,3]  #numpy allows this

array([ 8, 12, 16])

In [73]:
b[1:][3] #same line throws error in list also, 
# dont use [ ]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [77]:
b[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [79]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [81]:
b[2,0:3]

array([ 9, 10, 11])

In [82]:
b[1:,2]

array([ 7, 11, 15])