NUMPY - Numerical python

Here we can create nd array,
means we can create 1d array 2d array and 3d array till n, litreally N.
- less memory requirement
- takes less time.

- Consider a scenario where i have 2 arrays each having 8 items, and i want an array C which will give me the addition of both these arrays items, consecutively.
- in normal python i'll be doing 8 iterations to achieve this task.
- but using numpy it will complete the same task in two chunks.(it will seprate the array in two big chunks and perform one by one)
- this process in Called, 
#### Vectorization.

In [2]:
import numpy as np

here we have created an alias name for numpy, rather than using things like numpy.add() we can just say np.add().


In [3]:
a = [1,2,3]
b = np.array(a)

print(a)
print(b)
print(type(b))

[1, 2, 3]
[1 2 3]
<class 'numpy.ndarray'>


we need to pass atleast one mandatory arguement, which should be "array-like"* in the np.array(*) function.

In [4]:
a = [1,2,3,'5','a',4.5]
b = np.array(a)
print(b)

['1' '2' '3' '5' 'a' '4.5']


NOTE - 
- here notice all elements are passed as integer, unlike list, numpy can store only homogeneous elements, means all should be of same type,
- so here, we are having strings also, so it converted all to string, since it is not possible to convert str to int, this is the best way it deals.

In [5]:
  a = [1,2,3,'5','a',4.5]
b = np.array(a, dtype = int)
print(b)

ValueError: invalid literal for int() with base 10: 'a'

- we use dtype in the np.array arguement, to specify we need all elements like this.

Expected error : we are trying to convert str into int.

In [6]:
a = [1,2,3,5,4.5]
b = np.array(a, dtype = int)
print(b)

[1 2 3 5 4]


It works fine here.

In [7]:
 a = [1,2,3,5,4.5]
b = np.array(a, dtype = float)
print(b)

[1.  2.  3.  5.  4.5]


In [8]:
a = [1,2,3,5,4.5]
b = np.array(a *3,dtype= int)
print(b)

[1 2 3 5 4 1 2 3 5 4 1 2 3 5 4]


np.ones()
np.zeroes()
np.full()
np.empty()

In [9]:
b = np.ones(5)
b

array([1., 1., 1., 1., 1.])

- so this np.ones() gives us 1's number of given times.
- default return type = float

In [10]:
b = np.ones(5,dtype=int)
b

array([1, 1, 1, 1, 1])

In [11]:
b = np.zeros(3)
b

array([0., 0., 0.])

In [12]:
b = np.zeros(3,dtype = int)
b

array([0, 0, 0])

In [13]:
b = np.ones((2,3),dtype=int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [14]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
b = np.zeros((3,4),dtype=int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [16]:
b = np.full(3)
b

TypeError: full() missing 1 required positional argument: 'fill_value'

In [17]:
b = np.full(3,2)
b

array([2, 2, 2])

In [18]:
b = np.full((3,4),2)
b

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

np.empty()

#### GPT

In [19]:
import numpy as np

# Create an empty array with a specified shape
empty_array = np.empty((3, 4))  # Creates a 3x4 array

print(empty_array)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


- So what happens, it creates a array which given x*y size but fill it with any garbage value.(anything random, in this case we get zero, but other session could be anything)

In [20]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)

print(b)
print(type(b))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


### Few more methods to create numpy arrays

In [3]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


In [22]:
a = np.arange(5,10,2)
a

array([5, 7, 9])

so it just returns 5 to 9 with step of 2

### numpy.linspace()

In [23]:
b = np.linspace(1,50)
b

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

- So it generated (start,end, sample_size(optional))
- default sample size - 50

In [24]:
b = np.linspace(1,50,10)
b

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

i wanted 10 values between 1 to 50. it gave me according to the sample size.
- just given 10 values which are at equal distance

In [25]:
b = np.linspace(1,50,10,dtype=int)
b

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

There is a function which gives us the opion to include or exclue last given range point.

In [27]:
b = np.linspace(1,50,10,dtype=int,endpoint=True)
b

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50])

In [28]:
b = np.linspace(1,50,10,dtype=int,endpoint=False)
b

array([ 1,  5, 10, 15, 20, 25, 30, 35, 40, 45])

See it ignores the last point, which is 50.

- Now we have two kind of similar function
- np.identity()
- np.eye()

In [30]:
b = np.identity(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

- it will give me a square matrix of given number.
- accepts one arguement

In [31]:
b = np.eye(4)
b

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
b = np.eye(4,3)
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

this eye function can take more than one arguement, x*y for example

In [35]:
b = np.identity(4,3)
b

TypeError: Cannot interpret '3' as a data type

Identity cant take it

## Random Function

In [37]:
b = np.random.rand(3)
b

array([0.47783267, 0.37471414, 0.23068984])

It gives me an array of size 3, which has random values between,
## 0-1

In [38]:
b = np.random.rand(3)
b

array([0.11054885, 0.29213841, 0.81386528])

see everytime it gives different values

In [40]:
b = np.random.rand(2,3)
b

array([[0.01395721, 0.58884254, 0.79049661],
       [0.41800476, 0.68138772, 0.15251308]])

- we can give multiple arguements also

lets try creating an array of size 10, which has values from 0-15

In [44]:
b = np.random.rand(10)*10
b

array([4.02326711, 3.34334212, 9.64054419, 6.8193558 , 1.97127779,
       5.89667075, 9.93034486, 5.37160021, 5.26312077, 6.45469516])

I tried but cant convert these to int,
- used dtype
- added int in front
nothing worked

In [53]:
import numpy as np

# Sample array with floating-point numbers
original_array = np.array([4.02326711, 3.34334212, 9.64054419, 6.8193558, 1.97127779, 5.89667075, 9.93034486, 5.37160021, 5.26312077, 6.45469516])

# Convert each element to int
integer_array = original_array.astype(int)

# Print the resulting integer array
print(integer_array)


[4 3 9 6 1 5 9 5 5 6]


NOTE - it only works for numpy array.

- if we had a list then?

In [52]:
# Sample list with floating-point numbers
original_list = [4.02326711, 3.34334212, 9.64054419, 6.8193558, 1.97127779, 5.89667075, 9.93034486, 5.37160021, 5.26312077, 6.45469516]

# Convert each element to int using list comprehension
integer_list = [int(x) for x in original_list]

# Print the resulting integer list
print(integer_list)


[4, 3, 9, 6, 1, 5, 9, 5, 5, 6]


#### np.random.randint()

In [46]:
random_array = np.random.randint(1, 100, size=(5, 5))
random_array

array([[48, 22, 36, 51, 72],
       [64, 85, 16, 31, 64],
       [41, 76, 71, 57, 74],
       [57,  8, 89, 14, 81],
       [ 1, 49, 34, 39, 49]])

In [47]:
random_array = np.random.randint(1, 100, size=2)
random_array

array([61, 41])

In [51]:
import numpy as np

# Generate a random integer between a low (inclusive) and high (exclusive) value
# random_integer1 = np.random.randint(low, high, size)
# random_integer1

# Example 1: Generate a random integer between 0 (inclusive) and 10 (exclusive)
random_number2 = np.random.randint(0, 10)
print(random_number2)

# Example 2: Generate an array of random integers between 1 (inclusive) and 100 (exclusive) of size 5x5
random_array3 = np.random.randint(1, 100, size=(5, 5))
print(random_array3)

# Example 3: Generate a single random integer between 0 (inclusive) and 2 (exclusive)
random_binary4 = np.random.randint(0, 2)
print(random_binary4)

0
[[19 47 95 73 94]
 [ 3 82 58 20 50]
 [29 38 22 58 49]
 [68 14  5 24 54]
 [93 56 50 13 44]]
1


Exercise : mcq

In [55]:
a = np.array([0, 1, 2, 3])
a.shape

(4,)

 In NumPy, the shape of an array is represented as a tuple where each element of the tuple corresponds to the size of one dimension of the array.

In [56]:
np.random.rand()

0.6738436675469052

In [57]:
a = np.arange(9,50)
a

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
       26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [60]:
a = np.eye(5,6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [10]:
a = np.linspace(0,5,10)
a = [round(x,2) for x in a]
a

[0.0, 0.56, 1.11, 1.67, 2.22, 2.78, 3.33, 3.89, 4.44, 5.0]

In [12]:
a = np.eye(5,6)
a

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [17]:
a = np.linspace((0,5),8)
a

array([[0.        , 5.        ],
       [0.16326531, 5.06122449],
       [0.32653061, 5.12244898],
       [0.48979592, 5.18367347],
       [0.65306122, 5.24489796],
       [0.81632653, 5.30612245],
       [0.97959184, 5.36734694],
       [1.14285714, 5.42857143],
       [1.30612245, 5.48979592],
       [1.46938776, 5.55102041],
       [1.63265306, 5.6122449 ],
       [1.79591837, 5.67346939],
       [1.95918367, 5.73469388],
       [2.12244898, 5.79591837],
       [2.28571429, 5.85714286],
       [2.44897959, 5.91836735],
       [2.6122449 , 5.97959184],
       [2.7755102 , 6.04081633],
       [2.93877551, 6.10204082],
       [3.10204082, 6.16326531],
       [3.26530612, 6.2244898 ],
       [3.42857143, 6.28571429],
       [3.59183673, 6.34693878],
       [3.75510204, 6.40816327],
       [3.91836735, 6.46938776],
       [4.08163265, 6.53061224],
       [4.24489796, 6.59183673],
       [4.40816327, 6.65306122],
       [4.57142857, 6.71428571],
       [4.73469388, 6.7755102 ],
       [4.

In [21]:
a = np.linspace(0,5,9)
a

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])

In [28]:
import numpy as np

# Generate an array of 10 evenly spaced values between 0 and 1 (inclusive)
arr = np.linspace(1, 10, 10)

print(arr)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [30]:
arr, step = np.linspace(0, 1, 10, retstep=True)
print("Array:", arr)
print("Step size:", step)


Array: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
Step size: 0.1111111111111111


by using retstep it will give the stepsize.

In [39]:
a,step = np.linspace(0,5,10,retstep = True)
x = [round(z,2) for z in a]
print(x)
print(step)

[0.0, 0.56, 1.11, 1.67, 2.22, 2.78, 3.33, 3.89, 4.44, 5.0]
0.5555555555555556
